### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LukeMathWalker** [LukeMathWalker/linfa#7]
In terms of functionality, the mid-term end goal is to achieve an offering of ML algorithms and pre-processing routines comparable to what is currently available in Python's [`scikit-learn`](https://scikit-learn.org/stable/).

These algorithms can either be:
- re-implemented in Rust;
- re-exported from an existing Rust crate, if available on [crates.io](crates.io) with a compatible interface.

In no particular order, focusing on the main gaps:
- Clustering:
   - [ ] DBSCAN;
   - [ ] Spectral clustering;
   - [ ] Hierarchical clustering;
   - [ ] OPTICS.
- Preprocessing:
   - [ ] PCA
   - [ ] ICA
   - [ ] Normalisation
   - [ ] CountVectoriser
   - [ ] TFIDF
- Supervised Learning:
   - [ ] Linear regression;
   - [ ] Ridge regression;
   - [ ] LASSO;
   - [ ] Support vector machines;
   - [ ] Nearest Neighbours;
   - [ ] Gaussian processes;
   - [ ] Decision trees;
   - [ ] Random forest
   - [ ] Naive Bayes

The collection is on purpose loose and non-exhaustive - if there is an ML algorithm that you find yourself using often on a day to day, please feel free to contribute it :100:

**Comment by Nimpruda** [comment]
Hi, I'm eager to help I'll take Linear regression, Lasso and ridge.

**Comment by LukeMathWalker** [comment]
Cool! I worked a bit on linear regression a while ago - you can find a very vanilla implementation of it here: https://github.com/rust-ndarray/ndarray-examples/tree/master/linear_regression @Nimpruda

**Comment by InCogNiTo124** [comment]
What does `Normalization` mean, is it like `StandardScaler` or something else?

**Comment by LukeMathWalker** [comment]
Exactly @InCogNiTo124.

**Comment by ADMoreau** [comment]
This is an interesting project and I will work on the PCA implementation

**Comment by nestordemeure** [comment]
I am the author of the [friedrich](https://crates.io/crates/friedrich) crate which implements Gaussian Processes.

While it is still a work in progress, it is fully featured and I would be happy to help integrate it into the project if you have directions to do so.

**Comment by LukeMathWalker** [comment]
That would be awesome @nestordemeure - I'll have a look at the project and I'll get back to you! Should I open an issue on `friedrich`'s repository when I am ready? Or would you prefer it to be tracked here on the `linfa` repository?

**Comment by nestordemeure** [comment]
Both are ok with me.

An issue in friedrich's repository might help avoid overcrowning linfa with issues but do as you prefer.

**Comment by mstallmo** [comment]
I'd love to take the Nearest Neighbors implementation

**Comment by aeroaks** [comment]
HI, I am eager to help out. I am not really confident with Rust as of now. Would it be a good choice to pick up Normalisation or any other pre-processing tasks like PCA?

**Comment by milesgranger** [comment]
I think this is really great, I just started on a sklearn like implementation of their pipelines, [here](https://github.com/milesgranger/pipes/blob/master/src/minmax/mod.rs) but more or less for experimentation without anything serious. I'll be sure to keep my eye on issues/goals here and help out where I can. Thanks for the initiative! :clap:

**Comment by ChristopherRabotin** [comment]
Hi there! First off, I don't have any experience in ML, but I read a lot about it (and listen to way too many podcasts on the topic). I'm interested in jumping in. I have quite some experience developing in Rust, and specifically high fidelity simulation tools (cf [nyx](https://gitlab.com/chrisrabotin/nyx/) and [hifitime](https://github.com/ChristopherRabotin/hifitime/)).

I wrote an Ant Colony Optimizer in Rust. ACOs are great for traversing graphs which represent a solution space, a problem which is considered NP hard if I'm not mistaken. Is that something used at all in ML? If so, would it be of interest to this library, or is there a greater interest (for now) to focus on the problems listed in the first post?

Cheers

**Comment by Nimpruda** [comment]
Hi @ChristopherRabotin I've never heard of ACOs but as it's in relation with graphs you should check if it has any uses with Markov Chains.

**Comment by ChristopherRabotin** [comment]
So far, I haven't found how both can be used together. The closest I found was finding several papers which use Markov Chains to analyze ACOs.

**Comment by onehr** [comment]
I would like to take the Naive Bayes one.

**Comment by tyfarnan** [comment]
I'll take on Gaussian Processes.

**Comment by bplevin36** [comment]
I'll put some work towards the text tokenization algorithms (CountVectorizer and TFIDF).

**Comment by LukeMathWalker** [comment]
Please take a look at what is already out there before diving head down into a reimplementation @tyfarnan  - I haven't had the time to look at [friedrich](https://crates.io/crates/friedrich) by @nestordemeure (takinga break after the final push to release the blog post and related code 😅) but we should definitely start from there as well as the GP sub-module in [rusty-machine](https://crates.io/crates/rusty-machine).

**Comment by nestordemeure** [comment]
@tyfarnan, don't hesitate to contact me via an issue on [friedrich's repository](https://github.com/nestordemeure/friedrich) once @LukeMathWalker has explicited what is expected of code that is integrated into Linfa and how this integration will be done.

**Comment by DallasC** [comment]
I did a quick round up of crates that implement the algorithms listed on the roadmap. Probably missed quite a few too but this can be a good starting point.

It was just a quick search so I don't know how reliavent each crate is but I tried to make a note if the crate was old and unmaintained. Hopefully this can be useful for helping with algorithm design or saving us from having to reimplement something that is already there.

[Algo ecosystem gist](https://gist.github.com/DallasC/1d3d8b3fb5ee10322f140e642b78131c)

**Comment by LukeMathWalker** [comment]
Tracking `friedrich`<>`linfa` integration here: https://github.com/nestordemeure/friedrich/issues/1

**Comment by LukeMathWalker** [comment]
I have updated the Issue to make sure it's immediately clear who is working on what and what items are still looking for an owner 👍

**Comment by InCogNiTo124** [comment]
hey @LukeMathWalker could you add me next to the normalization? I plan to do it by New Year's as I'm still not very experienced with Rust, but I have an idea how to implement it

**Comment by LukeMathWalker** [comment]
Done @InCogNiTo124 :pray:

**Comment by xd009642** [comment]
Started implementing DBScan in #12.

Also if there are suggestions Gaussian Mixture Models would be cool

**Comment by LukeMathWalker** [comment]
Implementation of `DBSCAN` merged to master - thanks @xd009642 :pray:

**Comment by adamShimi** [comment]
Hi, really cool project!
I have a question concerning the scope: do you eventually want to have deep learning and reinforcement learning algorithms too? I guess I'm curious to know if adding them is the plan eventually, but you want to start with the easier stuff, or if you think along the line of the scikit dev themselves : [here](https://scikit-learn.org/stable/faq.html#why-is-there-no-support-for-deep-or-reinforcement-learning-will-there-be-support-for-deep-or-reinforcement-learning-in-scikit-learn).

Either way, I'll be glad to help spread the rust gospel. Right know I'm going through the [Reinforcement Learning book](http://incompleteideas.net/book/the-book.html), and I will implement some of the algorithms; if that's in the scope of linfa, I'll be glad to try adding them to it. If not, I plan to read through [Understanding Machine Learning](https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/understanding-machine-learning-theory-algorithms.pdf) afterwards, and thus will eventually reach some of the algorithms in the roadmap. Then I will help by implementing them. :)

**Comment by xd009642** [comment]
From previous discussions deep learning etc is out of scope for the same reasons as it is for sci-kit. @LukeMathWalker might have more to say about it or reinforcement learning :smile:

**Comment by adamShimi** [comment]
Ok, thanks.

**Comment by LukeMathWalker** [comment]
I would consider both of them to be out of scope for this project - it's already incredibly broad as it is right now :sweat_smile: 
I'd love to see something spawn up for reinforcement learning, especially gym environments!

**Comment by bytesnake** [comment]
Can you also include Non-Negative Matrix Factorization (NMF) in the list for pre-processing steps. Its a standard algorithm in NLP/audio enhancement and decomposes a matrix into the product of two positive valued matrices. (https://en.wikipedia.org/wiki/Non-negative_matrix_factorization)

One of the nice properties is that there is a simple incremental algorithm for solving the the problem, with simple modification for sparsity constraints.

**Comment by bytesnake** [comment]
For hierarchical clustering there is the wonderful [kodama](https://github.com/diffeo/kodama) crate. Its based on [this](https://arxiv.org/pdf/1109.2378.pdf) paper and implements a list of algorithms for hierarchical clustering (and chooses the fastest one). I think it would be a waste to re-implement them. Perhaps we can just re-export it in a module?

**Comment by bytesnake** [comment]
Please take a look at the PR https://github.com/rust-ndarray/ndarray-linalg/pull/184 which adds `TruncatedEig` and `TruncatedSvd` routines to the library. Both are based on the [LOBPCG](https://en.wikipedia.org/wiki/LOBPCG) algorithm and allows a iterative approach to eigenvalue and singular value decomposition. This is used in PCA, manifold learning (e.g. spectral clustering) and discriminant analysis and is therefore useful here. The algorithm takes the problem `A` as a function and provides fast solution to sparse problems.

**Comment by bytesnake** [comment]
Can you also add me to the spectral clustering task? Will try to implement classical Multidimensional Scaling. The t-SNE technique is interesting too, but requires more time because it is based on a custom optimization problem. Furthermore gaussian embedding is another interesting technique, I used recently, but requires at-least SGD for a single layer NN. See papers here:

* https://www.lcayton.com/resexam.pdf
* http://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf
* https://arxiv.org/abs/1707.03815

**Comment by leaen** [comment]
Hi there!

I've been working on an implementation of decision trees [here](https://github.com/leaen/linfa/tree/decision_trees). It's still a WIP and needs documentation but it's a start at least. Once it's a bit more polished I can look at random forests also.

**Comment by VirtualSpaceman** [comment]
Hello, if possible, I would like to assume the implementation of ICA algorithm. My implementation will take [this paper](http://www.ee.columbia.edu/~dpwe/e6820/papers/HyvO00-icatut.pdf) as a guide.

**Comment by quietlychris** [comment]
@VirtualSpaceman That would be great--any pull requests are very welcome

**Comment by bytesnake** [comment]
ordinary linear regression was added in #20, thanks to @Nimpruda and @paulkoerbitz

**Comment by bytesnake** [comment]
linear decision trees was added in #18, kudos to @mossbanay

**Comment by bytesnake** [comment]
fast Independent Component Analysis was added in #47, kudos to @VasanthakumarV

**Comment by xd009642** [comment]
I'm gonna start working on OPTICS at some point soon :eyes:

**Comment by Sauro98** [comment]
Hello, I am working on an implementation of the [Approximated DBSCAN](https://www.cse.cuhk.edu.hk/~taoyf/paper/tods17-dbscan.pdf) algorithm [here](https://crates.io/crates/appr_dbscan_rust) and I was wondering if that is something that could be interesting for this project. Right now it has all the basic functionalities implemented and I would happily make any changes to make it fit here

**Comment by quietlychris** [comment]
@Sauro98 I believe linfa currently an implementation of the vanilla DBSCAN algorithm [here](https://github.com/rust-ml/linfa/tree/master/linfa-clustering/src/dbscan), but an approximate version would be a great addition! It would be great if you could open a pull request following that same style under the `linfa-clustering` sub-crate (i.e. using the `appx_dbscan` vs. `dbscan`), in a way that maintains some closeness between the API for the existing algorithm and your own (` Dbscan::predict(&hyperparams, &dataset);` -> `AppxDbscan::predict(&hyperparams, &dataset);`), which I believe usually accepts data in the form of an ndarray `&Array2<f64>` structure variant. I'd also think it would be really interesting to see benchmarks comparing performance between the two!

**Comment by relf** [comment]
Hello, I've started to work on a port of sklearn Gaussian Mixture Model (mentioned by @xd009642 above). I would be happy to contribute to the <code>linfa-clustering</code> sub-crate. Btw, thanks for the linfa initiative which is really promising.

**Comment by bytesnake** [comment]
Gaussian Mixture Models were added in #56, thanks to @relf

**Comment by bytesnake** [comment]
Gaussian naïve Bayes was added in #51, kudos to @VasanthakumarV

**Comment by kno10** [comment]
Fast K-medoids (PAM, FasterPAM) implementations: https://crates.io/crates/kmedoids

**Comment by rrichardson** [comment]
Markov Chains was mentioned above, but I'd really like to see Hidden Markov Models. I think it'd fit better under the "supervised learning" set of algorithms, even though it has unsupervised applications as well.  
I made a toy project with https://github.com/paulkernfeld/hmmm a while back and it seemed solid enough. 
There are no API docs, but the code itself is quite small, and very well documented.

**Comment by bytesnake** [comment]
the Partial Least Squares family was added in #95, thanks to @relf

**Comment by jkabc123** [comment]
I'd like to implement Random Forrest.

**Comment by bytesnake** [comment]
Preprocessing with normalisation, count-vectorizer and tf-idf merged in #93, kudos to @Sauro98

**Comment by bytesnake** [comment]
Nearest neighbours merged in #120, thanks to @YuhanLiin

**Comment by mrleu** [comment]
hi all i'd like to help implement too. what's the best way to pick up a task?

**Comment by bytesnake** [comment]
> hi all i'd like to help implement too. what's the best way to pick up a task?

not difficult, just mention your interest here and I will add you to the list once you've submitted the initial draft :)

**Comment by vaijira** [comment]
Could it be added "causal inference" like https://github.com/microsoft/dowhy library or would be out of scope of linfa?

**Comment by ericschief** [comment]
Hi everyone, I've implemented the semi-supervised learning algorithm called dynamic label propagation using Rust. I'm getting accuracy score up to 98% for one of the datasets I've been using. I don't think this algorithm is very well known, but could it be added to the Linfa library?

**Comment by bytesnake** [comment]
> Could it be added "causal inference" like https://github.com/microsoft/dowhy library or would be out of scope for linfa?

there are many interesting pattern which linfa can learn from but we would need first to support graphical models

**Comment by vaijira** [comment]
@bytesnake I'm playing with it, creating graph and identification support. If one day i feel it can be ready i'll submit a PR. https://github.com/vaijira/linfa/tree/causal/algorithms/linfa-causal-inference

**Comment by YuhanLiin** [comment]
# Infrastructure Goals

Aside from just adding new algorithms, there are also some infrastructure tasks that will significantly improve the ergonomics and performance of Linfa. They are listed here in descending order of importance, in my opinion:

- [ ] #220: Python bindings allows `linfa` to target the same userbase as `scikit-learn`, broadening the reach of the project. Having Python benchmarks also allows a fair performance comparison between `linfa` and `scikit-learn`.
- [ ] #228: This task potentially allows removing BLAS dependencies from `linfa` completely, significantly increasing code quality. It also has the side-effect of increasing benchmark coverage.
- [ ] #103: More benchmarks allow us to make performance optimizations with confidence.
- [ ] #161: Allows users to have more visibility into the internals of longer-running algorithms, similar to other mainstream ML libraries.

**Comment by oojo12** [comment]
Can I work on adding LDA to linfa?

**Comment by bernardo-sb** [comment]
I've been working on some features like: Categorical Encoding, MAPE and random forest. How can I contribute?

**Comment by YuhanLiin** [comment]
> Can I work on adding Linear Discriminant Analysis to linfa? Here is a [link](https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html) to the Sklearn analog

Does LDA output the dimensionally-reduced data at all? If so it should go into `linfa-reduction`

**Comment by YuhanLiin** [comment]
> I've been working on some features like: Categorical Encoding, MAPE and random forest. How can I contribute?

Random forests are covered by [this PR](https://github.com/rust-ml/linfa/pull/229).

Categorical encoding would go into `linfa-preprocessing`. I'm pretty sure we don't have it but just check to make sure.

MAPE is a simple function that would go into `linfa/src/metrics_regression.rs`

**Comment by oojo12** [comment]
> > Can I work on adding Linear Discriminant Analysis to linfa? Here is a [link](https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html) to the Sklearn analog
> 
> Does LDA output the dimensionally-reduced data at all? If so it should go into `linfa-reduction`

It can (transform). It can also just be used to predict classes (predict). The parentheses hold the method analog in Sklearn. Is there a preference for which should be implemented? Also, I am still getting familiar with Rust so it may take a few weeks to get done.

**Comment by YuhanLiin** [comment]
Preferably implement both if possible.

**Comment by LundinMachine** [comment]
Are there plans to implement ridge regression in the linear sub-package?  Looking for models to contribute.

**Comment by LundinMachine** [comment]
What about imputation, similar to scikit imput?

**Comment by YuhanLiin** [comment]
We don't have that. That can go in `linfa-preprocessing`

**Comment by HridayM25** [comment]
Hi! 
Can I take up Least Angle Regression and Random Forests?
Also can we look to implement xgboost and adaboost?

**Comment by YuhanLiin** [comment]
#229 implements bootstrap aggregation, which is a generalization of random forests, so you could work on that.

xgboost and adaboost seem to both be ensemble algorithms that are not necessarily tied to decision trees (correct me if I'm wrong), so we should probably put them in a new algorithm crate called `linfa-emsemble` or something. Bootstrap aggregation should probably go in there as well.

**Comment by HridayM25** [comment]
Hello sir, thanks for the response. 
I will look into what you mentioned, but I will need to revise Rust as I have not really used it in some time. 

Also, you are right about xgboost and adaboost not being tied to decision trees, as they can be used with linear models and deep neural networks as well, but originally they were designed to improve the performance of decision trees.

**Comment by sebasv** [comment]
I'd like to contribute quantile regression

**Comment by giorgiozoppi** [comment]
I'd also would like to help this.

**Comment by AndersonYin** [comment]
I'm interested to implement the Least Angle Regression. I'd like to pick it up

**Comment by AndersonYin** [comment]
I'm interested in the least angle regression (lars). It seems that PR #115 was trying to implement it but it has paused for 3 years. So I guess it's basically abolished. I'm going to pick it up.

**Comment by giorgiozoppi** [comment]
I am interested in random forests.

**Comment by zenconnor** [comment]
@MarekJReid @giorgiozoppi did either of you take a chance at random forests?

**Comment by giorgiozoppi** [comment]
Gonna study working it today, i look into. At school we did this week. For python binding maturin is perfect. @zenconnor  should i look inside scitkit-learn?

**Comment by jamesaphoenix** [comment]
Do we have grid search functionality? Or should I simply loop over multiple model.fit calls sequentially? 

What's the easiest way to implement this for 3x clustering techniques?

I'm looking to use all of these: 
https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-clustering/examples/dbscan.rs
https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-clustering/examples/kmeans.rs
https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-clustering/examples/optics.rs

Also do I need to implement multi-core processing similar to joblib in python? Or is this handled by linfa?

Thanks!

**Comment by duskmoon314** [comment]
Hello. I want to ask if you accept algorithms that are out of the box with `scikit-learn`. For example, [scikit-multiflow](https://scikit-multiflow.github.io/) provides machine learning algorithms for streaming data, not covered by `scikit-learn`.

I want to use Rust to achieve machine learning on streaming data. I haven't found crates that suit my needs, so I may implement several algorithms. I wonder if I could integrate them into Linfa in the future.

**Comment by CldStlkr** [comment]
Hi! I'd like to contribute by implementing an Isolation Forest algorithm for anomaly detection, since I have experience using the scikit-learn implementation at work. While not explicitly listed in the roadmap, it would fit well with the ensemble learning category and help round out the unsupervised learning capabilities of linfa. I'll be working on this over the next few months.

**Comment by maxprogrammer007** [comment]
I would like to work on Random Forest.

**Comment by cyancirrus** [comment]
Hey is this still active project, i have RF, GBM impls in my lib and just threw in Kmeans and GMM today, also are we anywhere on linear-algebra? like randomized-k svd (there's an impl sorry built everything as a study so all uses NdArray i built myself), was thinking of doing like multidimensional fourier soon -- are ya'll still going?
